insert into members values(0000000000,                -- Adding entries to the table
                            "Admin",
                            "Admin",
                            "Root",
                            "0000",
                            "Neópolis",
                            "Natal",
                            "RN",
                            "00000-000",
                            null,
                            null,
                            '1995-05-24',
                            "admin@email.com",
                            "include.jpg",
                            "admin",
                            "admin");

insert into members values(2013017920,                -- Adding entries to the table
                            "Igor Macedo Silva",
                            "Ciência e Tecnologia",
                            "Rua Simon Bolivar",
                            "2876",
                            "Neópolis",
                            "Natal",
                            "RN",
                            "59080-540",
                            "(84)3424-2342",
                            "(84)99292-9239",
                            '1994-05-25',
                            "igormacedo@email.com",
                            "include.jpg",
                            "igormacedo",
                            "password");

insert into members values(2013017921,                -- Adding entries to the table
                            "Ian Macedo Silva",
                            "Engenharia Química",
                            "Rua Simon Bolivar",
                            "2876",
                            "Neópolis",
                            "Natal",
                            "RN",
                            "59080-540",
                            "(84)3424-2342",
                            "(84)99292-9239",
                            '1994-05-25',
                            "ianmacedo@email.com",
                            "include.jpg",
                            "ianmacedo",
                            "password");
